route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack_notifications'
receivers:
  - name: 'slack_notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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' #change this line to use your own configuration
        channel: '#monitoring'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
