global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus02'
    scrape_interval: 5s
    static_configs:
      - targets: ['20.86.102.209:9100'] # change the target IP to use your own server
  - job_name: 'prometheus01'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - alert_rules.yml
